# Generated by Django 4.2.7 on 2023-11-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='creationdate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
