# Generated by Django 4.2.7 on 2023-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_remove_category_creationdate_remove_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
