# Generated by Django 4.2.7 on 2023-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_category_description_alter_category_categoryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(blank=True, max_length=100, null=True)),
                ('packagename', models.CharField(blank=True, max_length=100, null=True)),
                ('Packageimage', models.ImageField(blank=True, null=True, upload_to='Profile')),
            ],
        ),
    ]
