# Generated by Django 4.2.7 on 2023-11-15 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_addpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpackage',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
