# Generated by Django 4.2.7 on 2023-11-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_addpackage_creationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplementname', models.CharField(blank=True, max_length=100, null=True)),
                ('supplementdetails', models.CharField(blank=True, max_length=100, null=True)),
                ('supplementemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('supplementkg', models.CharField(blank=True, max_length=100, null=True)),
                ('Pro_Image', models.ImageField(blank=True, null=True, upload_to='Profile')),
            ],
        ),
    ]
