# Generated by Django 4.2.7 on 2023-11-23 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_addsupplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsupplement',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
