# Generated by Django 4.2.7 on 2023-11-23 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_addsupplement_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsupplement',
            name='supplementkg',
            field=models.CharField(choices=[('1kg', '1kg'), ('3kg', '3kg'), ('5kg', '5kg')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
