# Generated by Django 4.2.7 on 2023-11-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_alter_addsupplement_supplementkg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsupplement',
            name='supplementkg',
        ),
        migrations.AddField(
            model_name='addsupplement',
            name='is_1kg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addsupplement',
            name='is_3kg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addsupplement',
            name='is_5kg',
            field=models.BooleanField(default=False),
        ),
    ]
