# Generated by Django 4.2.7 on 2023-11-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_remove_addsupplement_supplementkg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsupplement',
            name='is_1kg',
        ),
        migrations.RemoveField(
            model_name='addsupplement',
            name='is_3kg',
        ),
        migrations.RemoveField(
            model_name='addsupplement',
            name='is_5kg',
        ),
    ]
