# Generated by Django 4.2.7 on 2023-11-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_remove_addsupplement_is_1kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsupplement',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
