# Generated by Django 4.2.7 on 2023-12-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_addsupplement_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddSupplement',
        ),
    ]
