# Generated by Django 4.2.7 on 2023-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_contact_creationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('NameOnCard', models.CharField(blank=True, max_length=200, null=True)),
                ('CardNumber', models.IntegerField(blank=True, null=True)),
                ('ExpMonth', models.CharField(blank=True, max_length=200, null=True)),
                ('ExpYear', models.IntegerField(blank=True, null=True)),
                ('CVV', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
