# Generated by Django 4.2.7 on 2023-12-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile'),
        ),
    ]
