# Generated by Django 4.2.7 on 2023-12-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_alter_registerdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='Image',
        ),
    ]
