# Generated by Django 4.2.7 on 2023-12-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_registerdb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Pro'),
        ),
    ]
