# Generated by Django 4.2.7 on 2023-12-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0014_alter_registerdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
